// <auto-generated />
using System;
using HIS.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace HIS.Migrations
{
    [DbContext(typeof(HISDbContext))]
    [Migration("20250224020046_initz0224one")]
    partial class initz0224one
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.MySql)
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HIS.SettlementSystem.Department", b =>
                {
                    b.Property<int>("department_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("department_id"));

                    b.Property<string>("department_type")
                        .HasColumnType("longtext");

                    b.Property<string>("location")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<string>("phone")
                        .HasColumnType("longtext");

                    b.HasKey("department_id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HIS.SettlementSystem.Discount", b =>
                {
                    b.Property<int>("discount_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("discount_id"));

                    b.Property<decimal>("discount_percentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("valid_from")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("valid_until")
                        .HasColumnType("datetime(6)");

                    b.HasKey("discount_id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("HIS.SettlementSystem.Doctor", b =>
                {
                    b.Property<int>("doctor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("doctor_id"));

                    b.Property<int>("department_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<string>("phone")
                        .HasColumnType("longtext");

                    b.Property<string>("specialty")
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .HasColumnType("longtext");

                    b.HasKey("doctor_id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("HIS.SettlementSystem.FeeItem", b =>
                {
                    b.Property<int>("item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("item_id"));

                    b.Property<string>("category")
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<bool>("is_refundable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("item_id");

                    b.ToTable("FeeItems");
                });

            modelBuilder.Entity("HIS.SettlementSystem.Fee_Category", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("category_id"));

                    b.Property<string>("category_name")
                        .HasColumnType("longtext");

                    b.HasKey("category_id");

                    b.ToTable("Fee_Categorys");
                });

            modelBuilder.Entity("HIS.SettlementSystem.Fee_Detail", b =>
                {
                    b.Property<int>("detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("detail_id"));

                    b.Property<int>("item_id")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("settlement_id")
                        .HasColumnType("int");

                    b.HasKey("detail_id");

                    b.ToTable("Fee_Details");
                });

            modelBuilder.Entity("HIS.SettlementSystem.Hospital_Bill", b =>
                {
                    b.Property<int>("bill_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("bill_id"));

                    b.Property<decimal>("amount_paid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("bill_date")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("outstanding_balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("patient_id")
                        .HasColumnType("int");

                    b.Property<int>("record_id")
                        .HasColumnType("int");

                    b.Property<decimal>("total_amount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("bill_id");

                    b.ToTable("Hospital_Bills");
                });

            modelBuilder.Entity("HIS.SettlementSystem.InpatientRecord", b =>
                {
                    b.Property<int>("record_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("record_id"));

                    b.Property<DateTime>("admission_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("admission_reason")
                        .HasColumnType("longtext");

                    b.Property<int>("department_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("discharge_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("doctor_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_in_insurance")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("patient_id")
                        .HasColumnType("int");

                    b.Property<string>("room_type")
                        .HasColumnType("longtext");

                    b.HasKey("record_id");

                    b.ToTable("InpatientRecords");
                });

            modelBuilder.Entity("HIS.SettlementSystem.Insurance_Record", b =>
                {
                    b.Property<int>("insurance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("insurance_id"));

                    b.Property<double>("coverage")
                        .HasColumnType("double");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("insurance_number")
                        .HasColumnType("longtext");

                    b.Property<string>("insurance_type")
                        .HasColumnType("longtext");

                    b.Property<int>("patient_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("insurance_id");

                    b.ToTable("Insurance_Records");
                });

            modelBuilder.Entity("HIS.SettlementSystem.Patient", b =>
                {
                    b.Property<int>("patient_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("patient_id"));

                    b.Property<string>("emergency_contact")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("marital_status")
                        .HasColumnType("longtext");

                    b.Property<string>("patient_address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("patient_age")
                        .HasColumnType("int");

                    b.Property<string>("patient_blood_type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("patient_contact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("patient_gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("patient_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("patient_id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HIS.SettlementSystem.Payment_Method", b =>
                {
                    b.Property<int>("payment_method_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("payment_method_id"));

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("method_name")
                        .HasColumnType("longtext");

                    b.HasKey("payment_method_id");

                    b.ToTable("Payment_Methods");
                });

            modelBuilder.Entity("HIS.SettlementSystem.Payment_Record", b =>
                {
                    b.Property<int>("payment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("payment_id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("payment_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("payment_method")
                        .HasColumnType("longtext");

                    b.Property<int>("settlement_id")
                        .HasColumnType("int");

                    b.HasKey("payment_id");

                    b.ToTable("Payment_Records");
                });

            modelBuilder.Entity("HIS.SettlementSystem.Receipt", b =>
                {
                    b.Property<string>("receipt_id")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("receipt_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("receipt_number")
                        .HasColumnType("longtext");

                    b.Property<string>("settlement_id")
                        .HasColumnType("longtext");

                    b.HasKey("receipt_id");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("HIS.SettlementSystem.Refund_Record", b =>
                {
                    b.Property<int>("refund_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("refund_id"));

                    b.Property<decimal>("refund_amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("refund_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("refund_reason")
                        .HasColumnType("longtext");

                    b.Property<int>("settlement_id")
                        .HasColumnType("int");

                    b.HasKey("refund_id");

                    b.ToTable("Refund_Records");
                });

            modelBuilder.Entity("HIS.SettlementSystem.Settlement_Record", b =>
                {
                    b.Property<string>("settlement_id")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("discount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("outstanding_balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("patient_id")
                        .HasColumnType("longtext");

                    b.Property<decimal>("payment_amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("payment_method")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("settlement_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("settlement_type")
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.Property<decimal>("total_amount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("settlement_id");

                    b.ToTable("Settlement_Records");
                });
#pragma warning restore 612, 618
        }
    }
}
